stages:
  - test
  - build
  - debian

jobs:
  include:
    - stage: test
      go_import_path: nanny
      language: go
      go:
        - "1.x"
      script: 
        - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: build
      go_import_path: nanny
      language: go
      go:
        - "1.x"
      script: 
        - go get github.com/ahmetb/govvv
        - govvv build -pkg nanny/pkg/version
    - stage: debian
      env:
        - TRAVIS_DEBIAN_DISTRIBUTION="sid"
      sudo: required
      language: generic
      services:
        - docker
      script:
        - wget -O- http://travis.debian.net/script.sh | sh -